name: notify discord users on updates

on: [push]

jobs:
  send_notif:
    runs-on: ubuntu-latest
    steps:
    - name: send message
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
