name: notify discord users on updates
on: [push]
jobs:
  send_notif:
    runs-on: ubuntu-latest
    steps:
    - name: send notification to discord users
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        color: "#eb4034"
        username: "Desmond's GitHub Build Bot for ${{ github.repository }}"
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "content": "🚀 New push detected in the repository! Commit details: **${{ github.actor }}** just pushed to **${{ github.ref }}**."
                 "${{ github.actor}} made a ${{ github.action }} on ${{ github.repository }}"
               }' \
               "${{ secrets.WEBHOOK_ID }}"
